services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "CEPRE.virtual"
      MYSQL_PASSWORD: "CEPRE.virtual"
      MYSQL_DATABASE: "ceprevirtualbd"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  ceprevirtualbackend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://mysqldb:3306/ceprevirtualbd?createDatabaseIfNotExist=true&serverTimezone=UTC
      - DB_USER_NAME=root
      - DB_PASSWORD=CEPRE.virtual
      - FRONT_URL=https://ceprevirtual.vercel.app
    restart: always
    depends_on:
      mysqldb:
        condition: service_healthy
    # Usar un 'entrypoint' o script de espera si el contenedor de base de datos tarda más en levantarse.
    # Puedes agregar un 'wait-for-it' o similar para que espere a que MySQL esté listo.

volumes:
  mysql-data:
    external: false